-- AlterTable
ALTER TABLE `FloorPlan`
    ADD COLUMN `configurationLabel` VARCHAR(191) NULL,
    ADD COLUMN `status` VARCHAR(191) NULL DEFAULT 'Active',
    ADD COLUMN `unitStream` VARCHAR(191) NULL DEFAULT 'Sale Unit',
    ADD COLUMN `reraReference` VARCHAR(191) NULL,
    MODIFY COLUMN `bathrooms` DOUBLE NULL,
    ADD COLUMN `balconies` INTEGER NULL,
    ADD COLUMN `kitchenType` VARCHAR(191) NULL,
    ADD COLUMN `additionalRooms` JSON NULL,
    ADD COLUMN `applicableFloorFrom` INTEGER NULL,
    ADD COLUMN `applicableFloorTo` INTEGER NULL,
    ADD COLUMN `unitNumbers` TEXT NULL,
    ADD COLUMN `totalUnitsOfPlan` INTEGER NULL,
    ADD COLUMN `facing` VARCHAR(191) NULL,
    ADD COLUMN `cornerUnit` BOOLEAN NULL DEFAULT false,
    ADD COLUMN `view` JSON NULL,
    ADD COLUMN `autoCalc` BOOLEAN NULL DEFAULT true,
    ADD COLUMN `builtupArea` DOUBLE NULL,
    ADD COLUMN `loadingBasis` VARCHAR(191) NULL DEFAULT 'On Carpet',
    ADD COLUMN `balconyArea` DOUBLE NULL,
    ADD COLUMN `enclosedBalconyUtility` DOUBLE NULL,
    ADD COLUMN `flowerBedPocketTerrace` DOUBLE NULL,
    ADD COLUMN `serviceSlabAcLedge` DOUBLE NULL,
    ADD COLUMN `refugeAreaShare` DOUBLE NULL,
    ADD COLUMN `carParkingSlots` INTEGER NULL,
    ADD COLUMN `parkingType` VARCHAR(191) NULL,
    ADD COLUMN `twoWheelerSlots` INTEGER NULL,
    ADD COLUMN `basementStoreroom` DOUBLE NULL,
    ADD COLUMN `rateBasis` VARCHAR(191) NULL DEFAULT 'On Carpet',
    ADD COLUMN `floorRisePerSqft` DOUBLE NULL,
    ADD COLUMN `baseFloorForFloorRise` INTEGER NULL,
    ADD COLUMN `cornerPlcPercent` DOUBLE NULL,
    ADD COLUMN `viewPlcPercent` DOUBLE NULL,
    ADD COLUMN `facingPlcPercent` DOUBLE NULL,
    ADD COLUMN `clubMembership` DOUBLE NULL,
    ADD COLUMN `infrastructureDevelopmentCharges` DOUBLE NULL,
    ADD COLUMN `infrastructureDevelopmentChargeBasis` VARCHAR(191) NULL,
    ADD COLUMN `legalDocumentation` DOUBLE NULL,
    ADD COLUMN `gstPercent` DOUBLE NULL DEFAULT 5,
    ADD COLUMN `stampDutyPercent` DOUBLE NULL DEFAULT 6,
    ADD COLUMN `registrationPercent` DOUBLE NULL DEFAULT 1,
    ADD COLUMN `advanceMaintenanceMonths` INTEGER NULL,
    ADD COLUMN `maintenanceRatePerSqftPerMonth` DOUBLE NULL,
    ADD COLUMN `sinkingFundCorpus` DOUBLE NULL,
    ADD COLUMN `societyFormationCharges` DOUBLE NULL,
    ADD COLUMN `floorPlanImages` JSON NULL,
    ADD COLUMN `brochurePageReference` VARCHAR(191) NULL,
    ADD COLUMN `walkthrough3dLink` VARCHAR(191) NULL,
    ADD COLUMN `paymentPlan` VARCHAR(191) NULL,
    ADD COLUMN `allotmentLetterTemplate` VARCHAR(191) NULL,
    ADD COLUMN `agreementTemplate` VARCHAR(191) NULL;

-- Data migration for renamed field semantics.
UPDATE `FloorPlan`
SET
    `builtupArea` = COALESCE(`builtupArea`, `coverArea`),
    `loadingBasis` = COALESCE(`loadingBasis`, 'On Carpet'),
    `rateBasis` = COALESCE(`rateBasis`, 'On Carpet'),
    `unitStream` = COALESCE(`unitStream`, 'Sale Unit'),
    `status` = COALESCE(`status`, 'Active'),
    `autoCalc` = COALESCE(`autoCalc`, true),
    `gstPercent` = COALESCE(`gstPercent`, 5),
    `stampDutyPercent` = COALESCE(`stampDutyPercent`, 6),
    `registrationPercent` = COALESCE(`registrationPercent`, 1);
